Repository CRESYM/colib0.github.io, pull requests merged in 2024-11, with the labels that each got.

#239 Issue 235 - GENQEC SM model corrections
  pages/models/generations/GENQEC/GENQEC_blocks.png
  pages/models/generations/GENQEC/GENQEC_blocks.svg
  pages/models/generations/GENQEC/index.md
Labels: bug, enhancement, evaluate component

#242 Issue 223 - ExpLoad corrections
  pages/models/loads/ExpLoad/index.md
Labels: bug, enhancement, evaluate component

#240 Issue 225 - FD Load corrections
  pages/models/loads/FDLoad/index.md
Labels: bug, enhancement, evaluate component

#241 Issue 224 - ZIP Load corrections
  pages/models/loads/ZIPLoad/index.md
Labels: bug, enhancement, evaluate component

#245 Issue 230: Phasor Grid Following model
  pages/models/generations/Sources/VSC/PhasorGridFollowingVSC/index.md
Labels: enhancement

#252 Merge all PRs to main
  pages/models/generations/GENQEC/GENQEC_blocks.png
  pages/models/generations/GENQEC/GENQEC_blocks.svg
  pages/models/generations/GENQEC/index.md
  pages/models/generations/Sources/VSC/PhasorGridFollowingVSC/index.md
  pages/models/loads/ExpLoad/index.md
  pages/models/loads/FDLoad/index.md
  pages/models/loads/ZIPLoad/index.md
  pages/models/motors/SimpleMotor/MotorEquivalentCircuit.drawio
  pages/models/motors/SimpleMotor/MotorEquivalentCircuit.drawio.svg
  pages/models/motors/SimpleMotor/index.md
  pages/models/motors/WECC_Motor/Load Characteristic MOTORW_0001.svg
  pages/models/motors/WECC_Motor/index.md
  pages/models/motors/index.md
  pages/models/regulations/governor/GovCT2/drawings/GovCT2.drawio.svg
  pages/models/regulations/governor/GovHydro4/drawings/GovHydro4.drawio.svg
  pages/models/regulations/governor/GovHydro4/drawings/fig-gate-head-flow-characteristics-output-1.png
  pages/models/regulations/governor/GovHydro4/index.md
  pages/models/regulations/governor/GovSteamEU/drawings/GovSteamEU.drawio.svg
  pages/models/regulations/governor/GovSteamEU/drawings/SteamTurbineConfig.drawio.svg
  pages/models/regulations/governor/GovSteamEU/index.md
Labels: bug, enhancement, new component

#244 Issue 233: Changes on EMT STATCOM model
  pages/models/CompensationDevices/STATCOM/index.md
Labels: enhancement

#246 Issue 232: EMT Grid Following corrections
  pages/models/generations/Sources/VSC/EMTGridFollowingVSC/PI_antiwindup.svg
  pages/models/generations/Sources/VSC/EMTGridFollowingVSC/PI_antiwindup_alternative.svg
  pages/models/generations/Sources/VSC/EMTGridFollowingVSC/index.md
Labels: enhancement

#250 Issue 231 - EMT GFM VSC corrections
  pages/models/generations/Sources/VSC/EMTGridFormingVSC/index.md
Labels: enhancement

#251 Issue 229 - Phasor GFM VSC corrections
  pages/models/generations/Sources/VSC/PhasorGridFormingVSC/index.md
Labels: enhancement

#249 Diagram paths corrected
  pages/models/regulations/avr/AC1C/index.md
  pages/models/regulations/avr/AC6C/index.md
  pages/models/regulations/avr/AC7C/index.md
  pages/models/regulations/avr/AC8C/index.md
  pages/models/regulations/avr/AcRotatingExciter/index.md
  pages/models/regulations/avr/BBSEX1/index.md
  pages/models/regulations/avr/DC1C/index.md
  pages/models/regulations/avr/IEEEX2/index.md
  pages/models/regulations/avr/IEEX2A/index.md
  pages/models/regulations/avr/SCRX/index.md
  pages/models/regulations/avr/ST1C/index.md
  pages/models/regulations/avr/ST4C/index.md
  pages/models/regulations/avr/ST5C/index.md
  pages/models/regulations/avr/ST6C/index.md
  pages/models/regulations/avr/ST7C/index.md
  pages/models/regulations/avr/ST9C/index.md
  pages/models/regulations/governor/GAST/index.md
  pages/models/regulations/governor/HYGOV/index.md
  pages/models/regulations/governor/IEEEG1/index.md
  pages/models/regulations/governor/IEEEG2/index.md
  pages/models/regulations/governor/TGOV1/index.md
  pages/models/regulations/governor/TGOV3/index.md
  pages/models/regulations/pss/PSS1A/index.md
  pages/models/regulations/pss/PSS2C/index.md
  pages/models/regulations/pss/PSS3C/index.md
  pages/models/regulations/pss/PSS6C/index.md
Labels: bug, documentation
