Repository CRESYM/colib0.github.io, pull requests merged in 2024-12, with the labels that each got.

#258 Issue 228_missing references author guidelines
  _bibliography/references.bib
  pages/about/authorGuidelines.md
Labels: bug

#259 Issue 237_Remove list of references from Others folder
  pages/models/others/index.md
Labels: bug

#255 ID234 - GENTPF SM corrections
  pages/models/generations/GENTPJ/index.md
Labels: enhancement

#261 Fixed reported issues and incorporated review comment
  _bibliography/references.bib
  pages/about/authorGuidelines.md
  pages/models/generations/GENTPJ/index.md
  pages/models/others/index.md
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/4-VSC_benchmark.pdf
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/dyn_det_1.dat
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/dyn_det_2.dat
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/events.dst
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/lf_1_1150.dat
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/lf_2.dat
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/obs.dat
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/readme_4VSC.txt
  pages/testCases/converterDrivenStability/4VSCSystem/STEPPS/settings.dat
  pages/testCases/converterDrivenStability/4VSCSystem/index.md
Labels: bug, enhancement
