Repository CRESYM/colib0.github.io, pull requests merged in 2025-03, with the labels that each got.

#264 add wt type 3
  pages/models/generations/wind/iec_wt_type3/drawings/Grid_Protection.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/IEC_WT_meas.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_P.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_Q.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_communication.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_control_and_communication.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_CurrentLim.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3A.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3B.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3B_risingvalue.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3B_timer.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_P_control_type3.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_Q_control.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_Qlim.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_aerodynamic.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_generator_control_substructure_type3.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_mechanical.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_pitch.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_system.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_torque_pi.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/fig-lookup-table-omega-pref-output-1.png
  pages/models/generations/wind/iec_wt_type3/index.md
  pages/models/generations/wind/index.md
Labels: new component

#273 Add wt type 3 #264 to main
  pages/models/generations/wind/iec_wt_type3/drawings/Grid_Protection.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/IEC_WT_meas.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_P.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_Q.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_communication.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WP_control_and_communication.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_CurrentLim.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3A.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3B.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3B_risingvalue.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_GS_3B_timer.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_P_control_type3.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_Q_control.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_Qlim.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_aerodynamic.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_generator_control_substructure_type3.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_mechanical.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_pitch.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_system.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/WT_torque_pi.drawio.svg
  pages/models/generations/wind/iec_wt_type3/drawings/fig-lookup-table-omega-pref-output-1.png
  pages/models/generations/wind/iec_wt_type3/index.md
  pages/models/generations/wind/index.md
Labels: new component

#276 Merge pull request #274
  index.html
  pages/about/team.md
Labels: enhancement

#243 Description files and diagrams for standard IEEE limitations (oel, uel, scl)
  pages/models/regulations/avr/AC1C/index.md
  pages/models/regulations/avr/AC6C/index.md
  pages/models/regulations/avr/AC7C/index.md
  pages/models/regulations/avr/AC8C/index.md
  pages/models/regulations/avr/AcRotatingExciter/index.md
  pages/models/regulations/avr/BBSEX1/index.md
  pages/models/regulations/avr/DC1C/index.md
  pages/models/regulations/avr/SCRX/index.md
  pages/models/regulations/avr/ST1C/index.md
  pages/models/regulations/avr/ST4C/index.md
  pages/models/regulations/avr/ST5C/index.md
  pages/models/regulations/avr/ST6C/index.md
  pages/models/regulations/avr/ST7C/index.md
  pages/models/regulations/avr/ST9C/index.md
  pages/models/regulations/avr/index.md
  pages/models/regulations/governor/GAST/index.md
  pages/models/regulations/governor/IEEEG1/index.md
  pages/models/regulations/governor/IEEEG2/index.md
  pages/models/regulations/governor/TGOV1/index.md
  pages/models/regulations/governor/TGOV3/index.md
  pages/models/regulations/governor/index.md
  pages/models/regulations/oel/OEL2C/OEL2C.drawio
  pages/models/regulations/oel/OEL2C/OEL2C.drawio.svg
  pages/models/regulations/oel/OEL2C/OelReferenceCurrent.drawio
  pages/models/regulations/oel/OEL2C/OelReferenceCurrent.drawio.svg
  pages/models/regulations/oel/OEL2C/index.md
  pages/models/regulations/oel/OEL3C/OEL3C.drawio
  pages/models/regulations/oel/OEL3C/OEL3C.drawio.svg
  pages/models/regulations/oel/OEL3C/index.md
  pages/models/regulations/oel/OEL4C/OEL4C.drawio
  pages/models/regulations/oel/OEL4C/OEL4C.drawio.svg
  pages/models/regulations/oel/OEL4C/index.md
  pages/models/regulations/oel/OEL5C/OEL5C.drawio
  pages/models/regulations/oel/OEL5C/OEL5C.drawio.svg
  pages/models/regulations/oel/OEL5C/index.md
  pages/models/regulations/oel/index.md
  pages/models/regulations/pss/PSS1A/index.md
  pages/models/regulations/pss/PSS2C/index.md
  pages/models/regulations/pss/PSS3C/index.md
  pages/models/regulations/pss/PSS6C/index.md
  pages/models/regulations/scl/SCL1C/SCL1C.drawio
  pages/models/regulations/scl/SCL1C/SCL1C.drawio.svg
  pages/models/regulations/scl/SCL1C/index.md
  pages/models/regulations/scl/SCL2C/SCL2C.drawio
  pages/models/regulations/scl/SCL2C/SCL2C.drawio.svg
  pages/models/regulations/scl/SCL2C/SclReferenceCurrent.drawio
  pages/models/regulations/scl/SCL2C/SclReferenceCurrent.drawio.svg
  pages/models/regulations/scl/SCL2C/index.md
  pages/models/regulations/scl/index.md
  pages/models/regulations/uel/UEL1/UEL1.drawio
  pages/models/regulations/uel/UEL1/UEL1.drawio.svg
  pages/models/regulations/uel/UEL1/index.md
  pages/models/regulations/uel/UEL2C/UEL2C.drawio
  pages/models/regulations/uel/UEL2C/UEL2C.drawio.svg
  pages/models/regulations/uel/UEL2C/index.md
  pages/models/regulations/uel/index.md
Labels: documentation

#277 Merge pull request #243
  pages/models/regulations/avr/AC1C/index.md
  pages/models/regulations/avr/AC6C/index.md
  pages/models/regulations/avr/AC7C/index.md
  pages/models/regulations/avr/AC8C/index.md
  pages/models/regulations/avr/AcRotatingExciter/index.md
  pages/models/regulations/avr/BBSEX1/index.md
  pages/models/regulations/avr/DC1C/index.md
  pages/models/regulations/avr/SCRX/index.md
  pages/models/regulations/avr/ST1C/index.md
  pages/models/regulations/avr/ST4C/index.md
  pages/models/regulations/avr/ST5C/index.md
  pages/models/regulations/avr/ST6C/index.md
  pages/models/regulations/avr/ST7C/index.md
  pages/models/regulations/avr/ST9C/index.md
  pages/models/regulations/avr/index.md
  pages/models/regulations/governor/GAST/index.md
  pages/models/regulations/governor/IEEEG1/index.md
  pages/models/regulations/governor/IEEEG2/index.md
  pages/models/regulations/governor/TGOV1/index.md
  pages/models/regulations/governor/TGOV3/index.md
  pages/models/regulations/governor/index.md
  pages/models/regulations/oel/OEL2C/OEL2C.drawio
  pages/models/regulations/oel/OEL2C/OEL2C.drawio.svg
  pages/models/regulations/oel/OEL2C/OelReferenceCurrent.drawio
  pages/models/regulations/oel/OEL2C/OelReferenceCurrent.drawio.svg
  pages/models/regulations/oel/OEL2C/index.md
  pages/models/regulations/oel/OEL3C/OEL3C.drawio
  pages/models/regulations/oel/OEL3C/OEL3C.drawio.svg
  pages/models/regulations/oel/OEL3C/index.md
  pages/models/regulations/oel/OEL4C/OEL4C.drawio
  pages/models/regulations/oel/OEL4C/OEL4C.drawio.svg
  pages/models/regulations/oel/OEL4C/index.md
  pages/models/regulations/oel/OEL5C/OEL5C.drawio
  pages/models/regulations/oel/OEL5C/OEL5C.drawio.svg
  pages/models/regulations/oel/OEL5C/index.md
  pages/models/regulations/oel/index.md
  pages/models/regulations/pss/PSS1A/index.md
  pages/models/regulations/pss/PSS2C/index.md
  pages/models/regulations/pss/PSS3C/index.md
  pages/models/regulations/pss/PSS6C/index.md
  pages/models/regulations/scl/SCL1C/SCL1C.drawio
  pages/models/regulations/scl/SCL1C/SCL1C.drawio.svg
  pages/models/regulations/scl/SCL1C/index.md
  pages/models/regulations/scl/SCL2C/SCL2C.drawio
  pages/models/regulations/scl/SCL2C/SCL2C.drawio.svg
  pages/models/regulations/scl/SCL2C/SclReferenceCurrent.drawio
  pages/models/regulations/scl/SCL2C/SclReferenceCurrent.drawio.svg
  pages/models/regulations/scl/SCL2C/index.md
  pages/models/regulations/scl/index.md
  pages/models/regulations/uel/UEL1/UEL1.drawio
  pages/models/regulations/uel/UEL1/UEL1.drawio.svg
  pages/models/regulations/uel/UEL1/index.md
  pages/models/regulations/uel/UEL2C/UEL2C.drawio
  pages/models/regulations/uel/UEL2C/UEL2C.drawio.svg
  pages/models/regulations/uel/UEL2C/index.md
  pages/models/regulations/uel/index.md
Labels: enhancement, new component
