Repository CRESYM/colib0.github.io, pull requests merged in 2025-01, with the labels that each got.

#268 Update GitHub workflow file
  .github/workflows/jekyll.yml
Labels: bug

#265 63 epri gfm
  pages/models/generations/Sources/epri_gfm/drawings/DVOC_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/Droop_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/Grid_Forming.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/PLL_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/VSM_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/index.md
  pages/models/generations/synchronous_machines/GENQEC/GENQEC_blocks.svg
  pages/models/generations/synchronous_machines/GENQEC/index.md
  pages/models/generations/synchronous_machines/GENSAL/index.md
  pages/models/generations/synchronous_machines/GENTPJ/GENTPJ_blocks.png
  pages/models/generations/synchronous_machines/GENTPJ/index.md
  pages/models/generations/synchronous_machines/SM1/SM1_model_scheme.svg
  pages/models/generations/synchronous_machines/SM1/SM1equiv.svg
  pages/models/generations/synchronous_machines/SM1/SMSalientPoleScheme.svg
  pages/models/generations/synchronous_machines/SM1/SM_CapCurve.svg
  pages/models/generations/synchronous_machines/SM1/SM_CompCurves.svg
  pages/models/generations/synchronous_machines/SM1/SM_fixed_P.svg
  pages/models/generations/synchronous_machines/SM1/SM_fixed_ef.svg
  pages/models/generations/synchronous_machines/SM1/SM_rot_stat.svg
  pages/models/generations/synchronous_machines/SM1/index.md
  pages/models/generations/synchronous_machines/index.md
Labels: new component

#269 #63 add EPRI GFM
  pages/models/generations/Sources/epri_gfm/drawings/DVOC_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/Droop_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/Grid_Forming.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/PLL_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/drawings/VSM_Mode.drawio.svg
  pages/models/generations/Sources/epri_gfm/index.md
  pages/models/generations/synchronous_machines/GENQEC/GENQEC_blocks.svg
  pages/models/generations/synchronous_machines/GENQEC/index.md
  pages/models/generations/synchronous_machines/GENSAL/index.md
  pages/models/generations/synchronous_machines/GENTPJ/GENTPJ_blocks.png
  pages/models/generations/synchronous_machines/GENTPJ/index.md
  pages/models/generations/synchronous_machines/SM1/SM1_model_scheme.svg
  pages/models/generations/synchronous_machines/SM1/SM1equiv.svg
  pages/models/generations/synchronous_machines/SM1/SMSalientPoleScheme.svg
  pages/models/generations/synchronous_machines/SM1/SM_CapCurve.svg
  pages/models/generations/synchronous_machines/SM1/SM_CompCurves.svg
  pages/models/generations/synchronous_machines/SM1/SM_fixed_P.svg
  pages/models/generations/synchronous_machines/SM1/SM_fixed_ef.svg
  pages/models/generations/synchronous_machines/SM1/SM_rot_stat.svg
  pages/models/generations/synchronous_machines/SM1/index.md
  pages/models/generations/synchronous_machines/index.md
Labels: enhancement, new component
